### PR TITLE
kyleproxx: Add gesture typing library and define it

### PR DESCRIPTION
**Pull request by TheComputerGuy96**
LatinIME works with libjni_latinimegoogle.so from Android One MOB30D
https://github.com/opengapps/arm/blob/633d057fc482218d8a782424167a7889e5c9679a/lib/23/libjni_latinimegoogle.so

### CODE REVIEW

**Comment by minhng99** [comment]
No, this tree is generic and used by all version of CM KYLEPRO, merge android 6.0 lib to here will broke the rest.

**Comment by experienceRCOS** [comment]
No, because library will be simply unused on CM 11 and 12.1
Best solution: Create a cm-13.0 branch

**Comment by minhng99** [comment]
we don't really have any reason to integrate a prebuilt binary which don't affect the basic functionalizing of the device - this is vendor repo that mean only binary from samsung and necessary for device to be working will be in here, adding this helps nothing but potential something will broken in the future

**Comment by TheComputerGuy96** [comment]
I tested this on my CM 13.0 ROM (no issues)
Note: I used gesture typing library from Google Keyboard

**Pull request closed without merging**
